version: '3.1'

services:
  php-apache:
    build:
      context: ./docker/php-apache
      dockerfile: ./Dockerfile
    container_name: php-8.1-math
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8082:80
      - 8083:443  
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  database:
    image: mariadb:latest
    container_name: mariadb-math
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-example}
      MYSQL_DATABASE: maths
      MYSQL_USER: maths
      MYSQL_PASSWORD: maths
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-math
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - 8090:80
    environment:
      PMA_HOST: database
    networks:
      - app-network
    
  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: node-math
    restart: unless-stopped
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 5188:5188
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
